Feature/get logs endpoint
onyanko-pon/isucon_log_admin_backend pull request #9
Opened 2021-07-23 08:21 UTC by hiromi-mitsuoka

```
yarn sequelize-cli db:create
yarn sequelize-cli db:migrate 
arn sequelize-cli db:seed:all
```

2021-07-26 10:40 UTC, onyanko-pon commented on src/db/seeders/20210721091750-test-logs.js
> +  // down: async (queryInterface, Sequelize) => {
[nits]
これ消してしまいましょう

2021-07-26 10:50 UTC, onyanko-pon requested changes

2021-07-26 10:50 UTC, onyanko-pon commented on src/api/api.ts
> +    const log = await Log.findByPk(log_id)
[MUST]
これid検索でなかった場合に404返すようにしてほしい

2021-07-26 10:50 UTC, onyanko-pon commented on docker-compose.yml
> +    container_name: isucon-log-db
修正ありがとう

2021-07-26 10:50 UTC, onyanko-pon commented on src/api/api.ts
> +  const log_id = req.params.id
[IMO]
基本キャメルケースで統一したいです

2021-07-26 10:50 UTC, onyanko-pon commented on src/index.ts
> +const router = require('./api/api')
[IMO]
ファイル分割、`/api/index.ts`にしたい

2021-07-27 06:53 UTC, hiromi-mitsuoka commented on src/db/seeders/20210721091750-test-logs.js
> +  // down: async (queryInterface, Sequelize) => {
削除しました！

2021-07-27 07:00 UTC, hiromi-mitsuoka commented on src/api/api.ts
> +    const log = await Log.findByPk(log_id)
nullだとcatchされなかったので条件分岐で対応しました。対応の仕方が正しいか不安なため確認していただきたいです！6e673202f7d5a9231f4ee3c4420ba8a6616802be

2021-07-27 07:01 UTC, hiromi-mitsuoka commented on src/api/api.ts
> +  const log_id = req.params.id
修正しました！

2021-07-27 07:04 UTC, hiromi-mitsuoka commented on src/index.ts
> +const router = require('./api/api')
- routerのパスの変更
- - ファイル名変更（api/api.ts → api/index.ts）
の対応で適切か確認いただきたいです。

2021-07-27 09:23 UTC, onyanko-pon requested changes

2021-07-27 09:23 UTC, onyanko-pon commented on src/api/index.ts
> +    if (log === null) return res.status(404).json(`id=${logId}のlogは存在しません`)
```suggestion
    if (log === null) {
      return res.status(404).json({message: `id=${logId}のlogは存在しません`})
    }
```

2021-07-27 09:24 UTC, merged